### ISSUE TITLE
Linear Regression Variance Reduction Example

### ISSUE THREAD

**Issue by tjdodwell** [alan-turing-institute/pymc3#72]
I am a bit confused by example in MLDA_variance_reduction_linear_regression.ipynb

There appears to be just two levels, coarse and fine.

But in the Multilevel estimate we have Q_2_1 , Q_1_0 and Q_0 this suggests there are infact three levels?

**Comment by gmingas** [comment]
If you are talking about [this](https://github.com/alan-turing-institute/pymc3/blob/mlda/docs/source/notebooks/MLDA_variance_reduction_linear_regression.ipynb) notebook on branch mlda, there are two coarse models coarse_model_0 and coarse_model_1 defined in the same cell.
