### ISSUE TITLE
Q_0 and Q_1_0 are not stored in Variance Reduction Example

### ISSUE THREAD

**Issue by tjdodwell** [alan-turing-institute/pymc3#73]
I have implemented a slightly alternative version of the documented linear regression problem in branch 'feature/examplesPaper'

Follow the same process the @gmingas did for variance reduction. However, when I try and make the estimates and I look at

`trace2.stat_names`

I get only the following

`{'accept',
 'accepted',
 'base_scaling_beta0',
 'base_scaling_beta1',
 'base_scaling_sig2_log__',
 'tune'}`

i.e there is no Q_0 Q_1_0 for variance reduction.

**Comment by gmingas** [comment]
Can you add a link to the example?

My guess is that you are not passing the `variance_reduction=True` argument when instantiating your MLDA step.

Also, the names of the variables suggests you might be using an older version of the code (in the newer version you should have `base_scaling` only, that contains all variables, instead of separate ones for each variable).

**Comment by gmingas** [comment]
It might be a good idea to reclone the repository from scratch to make sure all the rebased branches are updated.

**Comment by tjdodwell** [comment]
@gmingas so I have now reclone and copied over. You will see a new branch 'paperExamples'

notebook is called 

pymc3/docs/source/notebooks/mlda_paper/MLDA_bodyFat.ipynb

I have set `variance_reduction = True`

`trace.stat_names` still generates the same as above. Sorry if it is me who has done something silly with version here.

**Comment by gmingas** [comment]
Hi Tim,

I ran the notebook in my computer and it creates the QoI normally.

I think the problem might be that you did not re-install pymc3 after updating the code so you are probable running all your examples with a very old version of our code.

You need to go to the root pymc3 dir and type `pip install -e .` in the terminal. This way it will update your local installation to use the code you have checked out atm. The `-e` flag means that you no longer need to do the same re-install every time you change the code. The changes will be applied automatically (it is a sort of development installation). 

This should work when you change branches too but if you do not see changes being applied automatically, rerun `pip install -e .` just in case before you seek other reasons.

Let me know if this helps.

Also, there are a couple of bugs in the notebooks code:
- `subsampling_rates=[subSampling]` should be `subsampling_rates=subSampling`
- `var_names = ['beta0', 'beta1', 'sig']` should be `var_names = ['beta0', 'beta1', 'sig2']`
- `reshape((numSamples + burnIn, numChains))` should be `reshape((numSamples, numChains))`

**Comment by tjdodwell** [comment]
`pip install -e`

gives the following error, any ideas?

**Comment by gmingas** [comment]
You did not paste the error message but the command should be `pip install -e .` (notice the full stop at the end). Also make sure you are in the root directory of the repository.

**Comment by tjdodwell** [comment]
Sorted thanks, realise I had installed `pymc3` via `pip install pymc3` originally. Started again and works all fine, including Q_0 etc. Super!
