### ISSUE TITLE
New astep functions for MLDA versions of the step methods.

### ISSUE THREAD

**Issue by mikkelbue** [alan-turing-institute/pymc3#80]
About the new astep functions that allow for using VR. I had a look at them today, and I was wondering, is there any reason, we can't do:
```
def astep(self, q0):
    
    q_new, stats = super().astep(q0)
    
    if self.mlda_variance_reduction:
        if stats[0]['accepted']:
            self.Q_last = self.model.Q.get_value()
        if self.sub_counter == self.mlda_subsampling_rate_above:
            self.sub_counter = 0
        self.Q_reg[self.sub_counter] = self.Q_last
        self.sub_counter += 1
    
    return q_new, stats
```
Rather than having to repeat all the code of the parent classes. I tried changing the code to this, and all the tests ran as expected.

**Comment by mikkelbue** [comment]
Changed this in commit https://github.com/alan-turing-institute/pymc3/commit/38e3d2b4e40884593f4b06ea71d42de5e4a5fadb.

Please revert, if there is something I have overlooked, but it seems to be working according to the tests.

**Comment by gmingas** [comment]
This looks good as long as the tests and notebooks run. Thanks for pointing it out!
