### ISSUE TITLE
Terminology of the model hierarchy in the code

### ISSUE THREAD

**Issue by mikkelbue** [alan-turing-institute/pymc3#81]
Since the VR was added, I fell like there is a bit of terminology confusion in the code. The VR functionality uses a variable called `self.mlda_subsampling_rate_above`, while the actual model hierarchy is labelled using e.g. `self.next_model`. I feel like the one metaphor "above" is vertical, while "next" is horizontal, and it is not clear that these terms refer to the same hierarchy.

I would like to stick to the "above" and "below" terminology, and hence rename "next_model" to "model_below" and so on, since I think it is more true to the multilevel philosophy.

Greg, do you mind if I go through the code and try to apply a uniform naming convention?

**Comment by gmingas** [comment]
@mikkelbue Feel free to change that in a new branch, also check the test_step.py file for any uses of those terms.

**Comment by mikkelbue** [comment]
@gmingas Great thanks, I'll have a look at that, then.

**Comment by mikkelbue** [comment]
Fixed in https://github.com/alan-turing-institute/pymc3/commit/4ea4c1fa3c02261c6a7b3a7af984bda7cbb5fd94
