### ISSUE TITLE
MLDA traces from CompoundStep base steppers fail to save as netcfd.

### ISSUE THREAD

**Issue by mikkelbue** [alan-turing-institute/pymc3#87]
When using CompoundStep, `base_scaling_stats["base_scaling"]` has entries equal to the number of samplers on the base level. The resulting sampler statistic - `trace.get_sampler_stats('base_scaling')` - is an array of arrays, rather than a multidimensional array. Since all other sampling stats are one-dimensional, running
```
trace = az.from_pymc3(trace)
trace.to_netcdf(savename)
```
fails.

I have been trying to find a workaround that will allow `base_scaling` to be truly multidimensional but I can't, not within the bounds of upstream PyMC3 code.

I suggest that we restrict base_scaling_stats["base_scaling"] to be collected, only when using block sampling to avoid this unwanted behaviour. I will fix this, if you approve, @gmingas.

**Comment by gmingas** [comment]
Good spot. I never tried this function with the trace. I chose to save `base_scaling` as an array of arrays (and use the generic `object` to characterise it in the stats array) as there was no other apparent way to save multidimensional arrays.

I am wondering what happens with simple Metropolis stats when you run it as compound. I expect only one dimension is saved in stats but havent checked the code in `sample` to confirm. Maybe we should just replicate this as it will cause the least number of issues and unexpected behaviour.

**Comment by mikkelbue** [comment]
Well I spotted it after running the benchmarks notebook, which uses that function. I suspect you ran the benchmarks before writing the code that allows for base statistics to be collected.

It's possible to replicate the behaviour of CompoundStep for simple Metropolis, where the stats are returned as a _list_ of dictionaries, one for each stepper. I think this is why the stats are always returned as a list: to accommodate the possibility that sometimes, there are actually multiple entries. But the problem with this is that the other entries in the stats dictionary, `accepted`, `accept` and `tune`, are not compound, since they come from the top level MLDA. And I didn't manage to find a solution that would accommodate both. Which is why I suggested to just drop base stats when we are using CompoundStep on the base.

I don't think it will break any pipelines, since the key name `base_scaling` is unique for MLDA, and some steppers just don't return stats at all, e.g. if `generates_stats = False`. But I can play around some more and see if I can find a more elegant solution, for consistency's sake.

**Comment by mikkelbue** [comment]
@gmingas This is fixed in new branch: https://github.com/alan-turing-institute/pymc3/tree/fix/base_scaling_stats.

`base_tuning_stats` now hold base information, and is a separate dictionary (multiple dictionaries for CompoundStep) from the MLDA stats. Consistency achieved.
