### ISSUE TITLE
Add variance reduction to MLDA-MCMC

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/pymc3#9]
- [x] Code that allows VR within MLDA
- [x] Example notebook
- [x] Write tests
- [x] Find why variance is large
- [x] Merge into mlda_develop

**Comment by gmingas** [comment]
[Here](https://github.com/alan-turing-institute/pymc3/blob/feature/variance_reduction_experiments/docs/source/notebooks/MLDA_variance_reduction.ipynb) is a notebook that contains a comparison between MLDA with and without variance reduction. 

I am running one MLDA run and keeping Q_2 from the top chain and also all the terms for VR (Q_0, Q_1_0, Q_2_1). The question is: Given I have N samples from MLDA, what is better to do, use Q_2 (standard estimate) or use the VR technique? The computational cost (per top level sample) is the same for both of them as you need to run a full MLDA in either case. 

You can see at the bottom of the notebook that the variances of Q_1_0, Q_2_1 and Q_0 are comparable with Q_2 and the same applies to the ratios Q_1_0 / ESS_Q_1_0 etc which capture the standard errors. So it seems there is no benefit from VR. I have also calculated this for various chunks of the sample, i.e. 200, 1000 and 2000 samples. The case with 1000 samples is effectively the same as [this](https://github.com/alan-turing-institute/pymc3/blob/feature/variance-reduction/docs/source/notebooks/MLDA_variance_reduction.ipynb) run and the results are very similar in terms of SE (it turns out I *was* calculating SE in the original run).

**Comment by gmingas** [comment]
Proposed exploration steps after discussing with Tim:
- Run 2 level example and compare expectations and variances
- Check if covariance of Q_1 and Q_0 is negative
- Larger resolutions gaps
- Increase boundary conditions constants
- Check code correctness - maybe use python test example

**Comment by gmingas** [comment]
@mikkelbue In the groundwater flow model I am currently using the `my_models[-2].solver.h(0.4, 0.4)` as the quantity of interest whose expectation variance we want to minimize. I notice that its value when estimated by the coarse and fine samplers is very close all of the time. 

To investigate the behaviour of the variance reduction method I want a Q that differs a lot between coarse and fine models. Do you have any recommendations on how to change lamb_cov, mkl, h_in, h_out or other paramters to achieve that?

**Comment by mikkelbue** [comment]
@gmingas How about just taking the measurement at a different point, slightly offset from (0.4, 0.4)? Otherwise changing the h_in could be an option.
