### ISSUE TITLE
MLDA introduction notebook not in contents table

### ISSUE THREAD

**Issue by gmingas** [alan-turing-institute/pymc3#90]
@mikkelbue 
Just realised we forgot to add the MLDA_introduction to the table of examples: 
https://github.com/pymc-devs/pymc3/blob/master/docs/source/notebooks/table_of_contents_examples.js

This could be raised as an issue directly in the upstream.

**Comment by mikkelbue** [comment]
Okay, I will do that. What would be the best way of making such a small change? Another PR?

**Comment by gmingas** [comment]
Yes, new PR, should be accepted quickly.

**Comment by mikkelbue** [comment]
Fixed in https://github.com/alan-turing-institute/pymc3/commit/b543865e448b82e19eb067d387646e233fcd563d
